---
#mode 运行模式（默认为0） 0:单例模式; 1:分布式
#no-web 是否以no-web模式运行（默认为0） 0:否; 1:是
#min_wait/max_wait 任务执行之间的最小、最大等待时间（默认为10/1000ms）

#只有mode为1时，params中如下参数才有效：slaves_num,master_port
  #slaves_num slaves数目（默认为当前机器cpu核数）
  #master_port master绑定端口号（默认5557）

#只有no-web为0时，params中如下参数才有效：port
  #port web端口号，默认8089

#只有no-web为1时，params中如下参数才有效：csv,c,r,run_time
  #csv 运行结果文件名
  #c 并发用户数
  #r 每秒请求数
  #run_time 运行时间
mode: 1
no_web: 1
min_wait: 100
max_wait: 1000
params:
  slaves_num: 4
  master_port: 5557
  port: 8089
  csv: locust
  c: 10
  r: 10
  run_time: 5m
#task 性能测试任务
task:
  #file 测试文件名，支持相对路径如test_xxx/text_xxx_file.py
  #class 测试类
  #function 测试方法
  #weight 任务选择的概率权重（默认1）
- file: test_demo.py
  class: test_demo
  function: test_httpbin_get
  weight: 2
- file: test_demo.py
  class: test_demo
  function: test_httpbin_post
  weight: 1
- file: test_demo.py
  class: test_demo
  function: test_webservice
  weight: 1