---
Http:
  Host: http://www.baidu.com
  Port: 80
  Path: "/"

Httpbin:
  Host: http://httpbin.org
  Port: 80
  Path: "/"

Dubbo:
  Host: http://192.168.57.1
  Port: 10888
  Service: com.service.dubbo.api
  Interface: AccountService

Mysql:
  Type: mysql
  Host: 192.168.1.1
  Port: 3306
  User: root
  Passwd: root
  Database: mysql

Sqlserver:
  Type: sqlserver
  Host: 192.168.1.1
  Port: 1433
  User: sa
  Passwd: sa
  Database: sqlserver

Redis:
  Type: Redis
  Server: 192.168.86.1:6379:2

Redis_Cluster:
  Type: Redis_Cluster
  Server: 192.168.57.1:7379,192.168.57.1:7380,192.168.57.1:7381,192.168.57.2:7379,192.168.57.2:7380,192.168.57.2:7381